

// Input: s = "ABAB", k = 2 
// Output: 4

function repeatingChar(s, k){
          
    let fq1 = {};
    
    for(let key of s){
        fq1[key] = (fq1[key] || 0) + 1
    }

    let max = 0;
    let maxVal = ''
    for(let key in fq1){
       if(fq1[key] > max) {max = fq1[key]; maxVal = key };
    }

    let res = s.split("");
    let left = 0;
    let maxCount = 0;

    for (let right = 0; right < s.length; right++) {
        if (res[right] != maxVal) {
            k--;
        }

        while (k < 0) {
            if (res[left] != maxVal) {
                k++;
            }
            left++;
        }

        maxCount = Math.max(maxCount, right - left + 1);


    }
    console.log(maxCount,"maxCountmaxCount")
}

function tester () {
    
}

// console.log(tester(),"TESTERRRR")
// console.log(repeatingChar("ABAB",2),"SASSSSS")


 function remove(arr){

   let result = arr.map(cur =>{
        delete cur.id;
        delete cur.offer_id;
        delete cur.posid;
     
        return { ...cur }

    } )


    console.log(result,"RESULT");
} 


console.log(remove(
    [
    {
     "id": 1,
     "game_id": 2023020024,
     "home_team_id": 8,
     "away_team_id": 16,
     "matchDate": "2023-10-14",
     "posid": "NULL",
     "week": 1,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 2,
     "game_id": 2023020025,
     "home_team_id": 5,
     "away_team_id": 20,
     "matchDate": "2023-10-14",
     "posid": "NULL",
     "week": 1,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 3,
     "game_id": 2023020029,
     "home_team_id": 22,
     "away_team_id": 23,
     "matchDate": "2023-10-14",
     "posid": "NULL",
     "week": 1,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 4,
     "game_id": 2023020044,
     "home_team_id": 18,
     "away_team_id": 22,
     "matchDate": "2023-10-17",
     "posid": "NULL",
     "week": 1,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 5,
     "game_id": 2023020048,
     "home_team_id": 54,
     "away_team_id": 25,
     "matchDate": "2023-10-17",
     "posid": "NULL",
     "week": 1,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 6,
     "game_id": 2023020068,
     "home_team_id": 13,
     "away_team_id": 23,
     "matchDate": "2023-10-21",
     "posid": "NULL",
     "week": 2,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 7,
     "game_id": 2023020070,
     "home_team_id": 14,
     "away_team_id": 10,
     "matchDate": "2023-10-21",
     "posid": "NULL",
     "week": 2,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 8,
     "game_id": 2023020077,
     "home_team_id": 22,
     "away_team_id": 52,
     "matchDate": "2023-10-21",
     "posid": "NULL",
     "week": 2,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 9,
     "game_id": 2023020082,
     "home_team_id": 7,
     "away_team_id": 8,
     "matchDate": "2023-10-23",
     "posid": "NULL",
     "week": 2,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 10,
     "game_id": 2023020097,
     "home_team_id": 26,
     "away_team_id": 53,
     "matchDate": "2023-10-24",
     "posid": "NULL",
     "week": 2,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 11,
     "game_id": 2023020121,
     "home_team_id": 8,
     "away_team_id": 52,
     "matchDate": "2023-10-28",
     "posid": "NULL",
     "week": 3,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 12,
     "game_id": 2023020124,
     "home_team_id": 23,
     "away_team_id": 3,
     "matchDate": "2023-10-28",
     "posid": "NULL",
     "week": 3,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 13,
     "game_id": 2023020129,
     "home_team_id": 22,
     "away_team_id": 20,
     "matchDate": "2023-10-29",
     "posid": "NULL",
     "week": 3,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 14,
     "game_id": 2023020131,
     "home_team_id": 4,
     "away_team_id": 12,
     "matchDate": "2023-10-30",
     "posid": "NULL",
     "week": 3,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 15,
     "game_id": 2023020142,
     "home_team_id": 20,
     "away_team_id": 25,
     "matchDate": "2023-11-01",
     "posid": "NULL",
     "week": 3,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 16,
     "game_id": 2023020170,
     "home_team_id": 55,
     "away_team_id": 20,
     "matchDate": "2023-11-04",
     "posid": "NULL",
     "week": 4,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 17,
     "game_id": 2023020172,
     "home_team_id": 23,
     "away_team_id": 25,
     "matchDate": "2023-11-04",
     "posid": "NULL",
     "week": 4,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 18,
     "game_id": 2023020179,
     "home_team_id": 23,
     "away_team_id": 22,
     "matchDate": "2023-11-06",
     "posid": "NULL",
     "week": 4,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 19,
     "game_id": 2023020182,
     "home_team_id": 2,
     "away_team_id": 30,
     "matchDate": "2023-11-07",
     "posid": "NULL",
     "week": 4,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 20,
     "game_id": 2023020190,
     "home_team_id": 10,
     "away_team_id": 9,
     "matchDate": "2023-11-08",
     "posid": "NULL",
     "week": 4,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 21,
     "game_id": 2023020213,
     "home_team_id": 9,
     "away_team_id": 20,
     "matchDate": "2023-11-11",
     "posid": "NULL",
     "week": 5,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 22,
     "game_id": 2023020215,
     "home_team_id": 10,
     "away_team_id": 23,
     "matchDate": "2023-11-11",
     "posid": "NULL",
     "week": 5,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 23,
     "game_id": 2023020234,
     "home_team_id": 18,
     "away_team_id": 24,
     "matchDate": "2023-11-14",
     "posid": "NULL",
     "week": 5,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 24,
     "game_id": 2023020236,
     "home_team_id": 52,
     "away_team_id": 1,
     "matchDate": "2023-11-14",
     "posid": "NULL",
     "week": 5,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 25,
     "game_id": 2023020239,
     "home_team_id": 22,
     "away_team_id": 55,
     "matchDate": "2023-11-15",
     "posid": "NULL",
     "week": 5,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 26,
     "game_id": 2023020258,
     "home_team_id": 6,
     "away_team_id": 8,
     "matchDate": "2023-11-18",
     "posid": "NULL",
     "week": 6,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 27,
     "game_id": 2023020260,
     "home_team_id": 20,
     "away_team_id": 2,
     "matchDate": "2023-11-18",
     "posid": "NULL",
     "week": 6,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 28,
     "game_id": 2023020265,
     "home_team_id": 23,
     "away_team_id": 55,
     "matchDate": "2023-11-18",
     "posid": "NULL",
     "week": 6,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 29,
     "game_id": 2023020267,
     "home_team_id": 30,
     "away_team_id": 10,
     "matchDate": "2023-11-19",
     "posid": "NULL",
     "week": 6,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 30,
     "game_id": 2023020274,
     "home_team_id": 25,
     "away_team_id": 3,
     "matchDate": "2023-11-20",
     "posid": "NULL",
     "week": 6,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 31,
     "game_id": 2023020313,
     "home_team_id": 21,
     "away_team_id": 20,
     "matchDate": "2023-11-25",
     "posid": "NULL",
     "week": 7,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 32,
     "game_id": 2023020314,
     "home_team_id": 28,
     "away_team_id": 23,
     "matchDate": "2023-11-25",
     "posid": "NULL",
     "week": 7,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 33,
     "game_id": 2023020319,
     "home_team_id": 18,
     "away_team_id": 52,
     "matchDate": "2023-11-26",
     "posid": "NULL",
     "week": 7,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 34,
     "game_id": 2023020326,
     "home_team_id": 28,
     "away_team_id": 15,
     "matchDate": "2023-11-27",
     "posid": "NULL",
     "week": 7,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 35,
     "game_id": 2023020335,
     "home_team_id": 22,
     "away_team_id": 54,
     "matchDate": "2023-11-28",
     "posid": "NULL",
     "week": 7,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 36,
     "game_id": 2023020361,
     "home_team_id": 8,
     "away_team_id": 17,
     "matchDate": "2023-12-02",
     "posid": "NULL",
     "week": 8,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 37,
     "game_id": 2023020363,
     "home_team_id": 5,
     "away_team_id": 4,
     "matchDate": "2023-12-02",
     "posid": "NULL",
     "week": 8,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 38,
     "game_id": 2023020367,
     "home_team_id": 20,
     "away_team_id": 23,
     "matchDate": "2023-12-02",
     "posid": "NULL",
     "week": 8,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 39,
     "game_id": 2023020376,
     "home_team_id": 8,
     "away_team_id": 55,
     "matchDate": "2023-12-04",
     "posid": "NULL",
     "week": 8,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 40,
     "game_id": 2023020391,
     "home_team_id": 22,
     "away_team_id": 12,
     "matchDate": "2023-12-06",
     "posid": "NULL",
     "week": 8,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 41,
     "game_id": 2023020413,
     "home_team_id": 10,
     "away_team_id": 18,
     "matchDate": "2023-12-09",
     "posid": "NULL",
     "week": 9,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 42,
     "game_id": 2023020419,
     "home_team_id": 23,
     "away_team_id": 12,
     "matchDate": "2023-12-09",
     "posid": "NULL",
     "week": 9,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 43,
     "game_id": 2023020421,
     "home_team_id": 22,
     "away_team_id": 1,
     "matchDate": "2023-12-10",
     "posid": "NULL",
     "week": 9,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 44,
     "game_id": 2023020425,
     "home_team_id": 24,
     "away_team_id": 52,
     "matchDate": "2023-12-10",
     "posid": "NULL",
     "week": 9,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 45,
     "game_id": 2023020436,
     "home_team_id": 19,
     "away_team_id": 17,
     "matchDate": "2023-12-12",
     "posid": "NULL",
     "week": 9,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 46,
     "game_id": 2023020464,
     "home_team_id": 8,
     "away_team_id": 2,
     "matchDate": "2023-12-16",
     "posid": "NULL",
     "week": 10,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 47,
     "game_id": 2023020466,
     "home_team_id": 10,
     "away_team_id": 5,
     "matchDate": "2023-12-16",
     "posid": "NULL",
     "week": 10,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 48,
     "game_id": 2023020467,
     "home_team_id": 52,
     "away_team_id": 21,
     "matchDate": "2023-12-16",
     "posid": "NULL",
     "week": 10,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 49,
     "game_id": 2023020490,
     "home_team_id": 2,
     "away_team_id": 22,
     "matchDate": "2023-12-19",
     "posid": "NULL",
     "week": 10,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 50,
     "game_id": 2023020497,
     "home_team_id": 26,
     "away_team_id": 55,
     "matchDate": "2023-12-20",
     "posid": "NULL",
     "week": 10,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 51,
     "game_id": 2023020520,
     "home_team_id": 9,
     "away_team_id": 5,
     "matchDate": "2023-12-23",
     "posid": "NULL",
     "week": 11,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 52,
     "game_id": 2023020526,
     "home_team_id": 26,
     "away_team_id": 20,
     "matchDate": "2023-12-23",
     "posid": "NULL",
     "week": 11,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 53,
     "game_id": 2023020527,
     "home_team_id": 23,
     "away_team_id": 28,
     "matchDate": "2023-12-23",
     "posid": "NULL",
     "week": 11,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 54,
     "game_id": 2023020538,
     "home_team_id": 16,
     "away_team_id": 52,
     "matchDate": "2023-12-27",
     "posid": "NULL",
     "week": 11,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 55,
     "game_id": 2023020539,
     "home_team_id": 20,
     "away_team_id": 55,
     "matchDate": "2023-12-27",
     "posid": "NULL",
     "week": 11,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 56,
     "game_id": 2023020564,
     "home_team_id": 30,
     "away_team_id": 52,
     "matchDate": "2023-12-31",
     "posid": "NULL",
     "week": 12,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 57,
     "game_id": 2023020569,
     "home_team_id": 24,
     "away_team_id": 22,
     "matchDate": "2023-12-31",
     "posid": "NULL",
     "week": 12,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 58,
     "game_id": 2023020577,
     "home_team_id": 25,
     "away_team_id": 8,
     "matchDate": "2024-01-02",
     "posid": "NULL",
     "week": 12,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 59,
     "game_id": 2023020578,
     "home_team_id": 30,
     "away_team_id": 20,
     "matchDate": "2024-01-02",
     "posid": "NULL",
     "week": 12,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 60,
     "game_id": 2023020584,
     "home_team_id": 23,
     "away_team_id": 9,
     "matchDate": "2024-01-02",
     "posid": "NULL",
     "week": 12,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 61,
     "game_id": 2023020611,
     "home_team_id": 1,
     "away_team_id": 23,
     "matchDate": "2024-01-06",
     "posid": "NULL",
     "week": 13,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 62,
     "game_id": 2023020615,
     "home_team_id": 22,
     "away_team_id": 9,
     "matchDate": "2024-01-06",
     "posid": "NULL",
     "week": 13,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 63,
     "game_id": 2023020617,
     "home_team_id": 16,
     "away_team_id": 20,
     "matchDate": "2024-01-07",
     "posid": "NULL",
     "week": 13,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 64,
     "game_id": 2023020621,
     "home_team_id": 3,
     "away_team_id": 23,
     "matchDate": "2024-01-08",
     "posid": "NULL",
     "week": 13,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 65,
     "game_id": 2023020624,
     "home_team_id": 21,
     "away_team_id": 6,
     "matchDate": "2024-01-08",
     "posid": "NULL",
     "week": 13,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 66,
     "game_id": 2023020660,
     "home_team_id": 8,
     "away_team_id": 22,
     "matchDate": "2024-01-13",
     "posid": "NULL",
     "week": 14,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 67,
     "game_id": 2023020662,
     "home_team_id": 10,
     "away_team_id": 21,
     "matchDate": "2024-01-13",
     "posid": "NULL",
     "week": 14,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 68,
     "game_id": 2023020673,
     "home_team_id": 29,
     "away_team_id": 23,
     "matchDate": "2024-01-15",
     "posid": "NULL",
     "week": 14,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 69,
     "game_id": 2023020677,
     "home_team_id": 5,
     "away_team_id": 55,
     "matchDate": "2024-01-15",
     "posid": "NULL",
     "week": 14,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 70,
     "game_id": 2023020688,
     "home_team_id": 22,
     "away_team_id": 10,
     "matchDate": "2024-01-16",
     "posid": "NULL",
     "week": 14,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 71,
     "game_id": 2023020714,
     "home_team_id": 20,
     "away_team_id": 22,
     "matchDate": "2024-01-20",
     "posid": "NULL",
     "week": 15,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 72,
     "game_id": 2023020724,
     "home_team_id": 6,
     "away_team_id": 52,
     "matchDate": "2024-01-22",
     "posid": "NULL",
     "week": 15,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 73,
     "game_id": 2023020726,
     "home_team_id": 18,
     "away_team_id": 13,
     "matchDate": "2024-01-22",
     "posid": "NULL",
     "week": 15,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 74,
     "game_id": 2023020728,
     "home_team_id": 23,
     "away_team_id": 16,
     "matchDate": "2024-01-22",
     "posid": "NULL",
     "week": 15,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 75,
     "game_id": 2023020740,
     "home_team_id": 10,
     "away_team_id": 52,
     "matchDate": "2024-01-24",
     "posid": "NULL",
     "week": 15,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 76,
     "game_id": 2023020782,
     "home_team_id": 10,
     "away_team_id": 2,
     "matchDate": "2024-02-05",
     "posid": "NULL",
     "week": 16,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 77,
     "game_id": 2023020784,
     "home_team_id": 7,
     "away_team_id": 25,
     "matchDate": "2024-02-06",
     "posid": "NULL",
     "week": 16,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 78,
     "game_id": 2023020788,
     "home_team_id": 5,
     "away_team_id": 52,
     "matchDate": "2024-02-06",
     "posid": "NULL",
     "week": 16,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 79,
     "game_id": 2023020789,
     "home_team_id": 15,
     "away_team_id": 8,
     "matchDate": "2024-02-06",
     "posid": "NULL",
     "week": 16,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 80,
     "game_id": 2023020790,
     "home_team_id": 54,
     "away_team_id": 22,
     "matchDate": "2024-02-06",
     "posid": "NULL",
     "week": 16,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 81,
     "game_id": 2023020814,
     "home_team_id": 52,
     "away_team_id": 5,
     "matchDate": "2024-02-10",
     "posid": "NULL",
     "week": 17,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 82,
     "game_id": 2023020818,
     "home_team_id": 15,
     "away_team_id": 23,
     "matchDate": "2024-02-11",
     "posid": "NULL",
     "week": 17,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 83,
     "game_id": 2023020833,
     "home_team_id": 22,
     "away_team_id": 17,
     "matchDate": "2024-02-13",
     "posid": "NULL",
     "week": 17,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 84,
     "game_id": 2023020827,
     "home_team_id": 10,
     "away_team_id": 19,
     "matchDate": "2024-02-13",
     "posid": "NULL",
     "week": 17,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 85,
     "game_id": 2023020823,
     "home_team_id": 6,
     "away_team_id": 14,
     "matchDate": "2024-02-13",
     "posid": "NULL",
     "week": 17,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 86,
     "game_id": 2023020859,
     "home_team_id": 1,
     "away_team_id": 4,
     "matchDate": "2024-02-17",
     "posid": "NULL",
     "week": 18,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 87,
     "game_id": 2023020857,
     "home_team_id": 8,
     "away_team_id": 15,
     "matchDate": "2024-02-17",
     "posid": "NULL",
     "week": 18,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 88,
     "game_id": 2023020871,
     "home_team_id": 53,
     "away_team_id": 22,
     "matchDate": "2024-02-19",
     "posid": "NULL",
     "week": 18,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 89,
     "game_id": 2023020869,
     "home_team_id": 30,
     "away_team_id": 23,
     "matchDate": "2024-02-19",
     "posid": "NULL",
     "week": 18,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 90,
     "game_id": 2023020868,
     "home_team_id": 19,
     "away_team_id": 10,
     "matchDate": "2024-02-19",
     "posid": "NULL",
     "week": 18,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 91,
     "game_id": 2023020912,
     "home_team_id": 22,
     "away_team_id": 20,
     "matchDate": "2024-02-24",
     "posid": "NULL",
     "week": 19,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 92,
     "game_id": 2023020918,
     "home_team_id": 7,
     "away_team_id": 12,
     "matchDate": "2024-02-25",
     "posid": "NULL",
     "week": 19,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 93,
     "game_id": 2023020923,
     "home_team_id": 15,
     "away_team_id": 9,
     "matchDate": "2024-02-26",
     "posid": "NULL",
     "week": 19,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 94,
     "game_id": 2023020937,
     "home_team_id": 23,
     "away_team_id": 5,
     "matchDate": "2024-02-27",
     "posid": "NULL",
     "week": 19,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 95,
     "game_id": 2023020935,
     "home_team_id": 20,
     "away_team_id": 26,
     "matchDate": "2024-02-27",
     "posid": "NULL",
     "week": 19,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 96,
     "game_id": 2023020967,
     "home_team_id": 19,
     "away_team_id": 30,
     "matchDate": "2024-03-02",
     "posid": "NULL",
     "week": 20,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 97,
     "game_id": 2023020964,
     "home_team_id": 10,
     "away_team_id": 3,
     "matchDate": "2024-03-02",
     "posid": "NULL",
     "week": 20,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 98,
     "game_id": 2023020974,
     "home_team_id": 22,
     "away_team_id": 5,
     "matchDate": "2024-03-03",
     "posid": "NULL",
     "week": 20,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 99,
     "game_id": 2023020971,
     "home_team_id": 7,
     "away_team_id": 52,
     "matchDate": "2024-03-03",
     "posid": "NULL",
     "week": 20,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 100,
     "game_id": 2023020981,
     "home_team_id": 6,
     "away_team_id": 22,
     "matchDate": "2024-03-05",
     "posid": "NULL",
     "week": 20,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 101,
     "game_id": 2023021019,
     "home_team_id": 23,
     "away_team_id": 52,
     "matchDate": "2024-03-09",
     "posid": "NULL",
     "week": 21,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 102,
     "game_id": 2023021024,
     "home_team_id": 12,
     "away_team_id": 20,
     "matchDate": "2024-03-10",
     "posid": "NULL",
     "week": 21,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 103,
     "game_id": 2023021022,
     "home_team_id": 5,
     "away_team_id": 22,
     "matchDate": "2024-03-10",
     "posid": "NULL",
     "week": 21,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 104,
     "game_id": 2023021029,
     "home_team_id": 52,
     "away_team_id": 15,
     "matchDate": "2024-03-11",
     "posid": "NULL",
     "week": 21,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 105,
     "game_id": 2023021035,
     "home_team_id": 4,
     "away_team_id": 28,
     "matchDate": "2024-03-12",
     "posid": "NULL",
     "week": 21,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 106,
     "game_id": 2023021070,
     "home_team_id": 22,
     "away_team_id": 21,
     "matchDate": "2024-03-16",
     "posid": "NULL",
     "week": 22,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 107,
     "game_id": 2023021067,
     "home_team_id": 10,
     "away_team_id": 12,
     "matchDate": "2024-03-16",
     "posid": "NULL",
     "week": 22,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 108,
     "game_id": 2023021080,
     "home_team_id": 20,
     "away_team_id": 15,
     "matchDate": "2024-03-18",
     "posid": "NULL",
     "week": 22,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 109,
     "game_id": 2023021094,
     "home_team_id": 54,
     "away_team_id": 14,
     "matchDate": "2024-03-19",
     "posid": "NULL",
     "week": 22,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 110,
     "game_id": 2023021090,
     "home_team_id": 22,
     "away_team_id": 8,
     "matchDate": "2024-03-19",
     "posid": "NULL",
     "week": 22,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 111,
     "game_id": 2023021133,
     "home_team_id": 55,
     "away_team_id": 8,
     "matchDate": "2024-03-24",
     "posid": "NULL",
     "week": 23,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 112,
     "game_id": 2023021128,
     "home_team_id": 9,
     "away_team_id": 22,
     "matchDate": "2024-03-24",
     "posid": "NULL",
     "week": 23,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 113,
     "game_id": 2023021127,
     "home_team_id": 12,
     "away_team_id": 10,
     "matchDate": "2024-03-24",
     "posid": "NULL",
     "week": 23,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 114,
     "game_id": 2023021134,
     "home_team_id": 19,
     "away_team_id": 54,
     "matchDate": "2024-03-25",
     "posid": "NULL",
     "week": 23,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 115,
     "game_id": 2023021142,
     "home_team_id": 52,
     "away_team_id": 22,
     "matchDate": "2024-03-26",
     "posid": "NULL",
     "week": 23,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 116,
     "game_id": 2023021176,
     "home_team_id": 15,
     "away_team_id": 6,
     "matchDate": "2024-03-30",
     "posid": "NULL",
     "week": 24,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 117,
     "game_id": 2023021170,
     "home_team_id": 7,
     "away_team_id": 10,
     "matchDate": "2024-03-30",
     "posid": "NULL",
     "week": 24,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 118,
     "game_id": 2023021180,
     "home_team_id": 23,
     "away_team_id": 24,
     "matchDate": "2024-03-31",
     "posid": "NULL",
     "week": 24,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 119,
     "game_id": 2023021187,
     "home_team_id": 52,
     "away_team_id": 26,
     "matchDate": "2024-04-01",
     "posid": "NULL",
     "week": 24,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 120,
     "game_id": 2023021186,
     "home_team_id": 19,
     "away_team_id": 22,
     "matchDate": "2024-04-01",
     "posid": "NULL",
     "week": 24,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 121,
     "game_id": 2023021227,
     "home_team_id": 26,
     "away_team_id": 23,
     "matchDate": "2024-04-06",
     "posid": "NULL",
     "week": 25,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 122,
     "game_id": 2023021224,
     "home_team_id": 9,
     "away_team_id": 1,
     "matchDate": "2024-04-06",
     "posid": "NULL",
     "week": 25,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 123,
     "game_id": 2023021233,
     "home_team_id": 1,
     "away_team_id": 18,
     "matchDate": "2024-04-07",
     "posid": "NULL",
     "week": 25,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 124,
     "game_id": 2023021232,
     "home_team_id": 15,
     "away_team_id": 9,
     "matchDate": "2024-04-07",
     "posid": "NULL",
     "week": 25,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 125,
     "game_id": 2023021238,
     "home_team_id": 23,
     "away_team_id": 54,
     "matchDate": "2024-04-08",
     "posid": "NULL",
     "week": 25,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 126,
     "game_id": 2023021277,
     "home_team_id": 10,
     "away_team_id": 17,
     "matchDate": "2024-04-13",
     "posid": "NULL",
     "week": 26,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 127,
     "game_id": 2023021286,
     "home_team_id": 20,
     "away_team_id": 53,
     "matchDate": "2024-04-14",
     "posid": "NULL",
     "week": 26,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 128,
     "game_id": 2023021283,
     "home_team_id": 19,
     "away_team_id": 55,
     "matchDate": "2024-04-14",
     "posid": "NULL",
     "week": 26,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 129,
     "game_id": 2023021298,
     "home_team_id": 8,
     "away_team_id": 17,
     "matchDate": "2024-04-16",
     "posid": "NULL",
     "week": 26,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
     "id": 130,
     "game_id": 2023021306,
     "home_team_id": 53,
     "away_team_id": 22,
     "matchDate": "2024-04-17",
     "posid": "NULL",
     "week": 26,
     "banner": 2,
     "winner": "NULL",
     "offer_id": "NULL",
     "lastUpdated": "NULL"
    },
    {
       "id": 1,
       "game_id": 2023020025,
       "home_team_id": 5,
       "away_team_id": 20,
       "matchDate": "2023-10-14",
       "posid": "NULL",
       "week": 1,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 2,
       "game_id": 2023020029,
       "home_team_id": 22,
       "away_team_id": 23,
       "matchDate": "2023-10-14",
       "posid": "NULL",
       "week": 1,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 3,
       "game_id": 2023020038,
       "home_team_id": 10,
       "away_team_id": 16,
       "matchDate": "2023-10-16",
       "posid": "NULL",
       "week": 1,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 4,
       "game_id": 2023020043,
       "home_team_id": 2,
       "away_team_id": 53,
       "matchDate": "2023-10-17",
       "posid": "NULL",
       "week": 1,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 5,
       "game_id": 2023020049,
       "home_team_id": 9,
       "away_team_id": 15,
       "matchDate": "2023-10-18",
       "posid": "NULL",
       "week": 1,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 6,
       "game_id": 2023020069,
       "home_team_id": 8,
       "away_team_id": 15,
       "matchDate": "2023-10-21",
       "posid": "NULL",
       "week": 2,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 7,
       "game_id": 2023020070,
       "home_team_id": 14,
       "away_team_id": 10,
       "matchDate": "2023-10-21",
       "posid": "NULL",
       "week": 2,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 8,
       "game_id": 2023020077,
       "home_team_id": 22,
       "away_team_id": 52,
       "matchDate": "2023-10-21",
       "posid": "NULL",
       "week": 2,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 9,
       "game_id": 2023020082,
       "home_team_id": 7,
       "away_team_id": 8,
       "matchDate": "2023-10-23",
       "posid": "NULL",
       "week": 2,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 10,
       "game_id": 2023020084,
       "home_team_id": 29,
       "away_team_id": 24,
       "matchDate": "2023-10-24",
       "posid": "NULL",
       "week": 2,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 11,
       "game_id": 2023020121,
       "home_team_id": 8,
       "away_team_id": 52,
       "matchDate": "2023-10-28",
       "posid": "NULL",
       "week": 3,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 12,
       "game_id": 2023020122,
       "home_team_id": 18,
       "away_team_id": 10,
       "matchDate": "2023-10-28",
       "posid": "NULL",
       "week": 3,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 13,
       "game_id": 2023020129,
       "home_team_id": 22,
       "away_team_id": 20,
       "matchDate": "2023-10-29",
       "posid": "NULL",
       "week": 3,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 14,
       "game_id": 2023020130,
       "home_team_id": 6,
       "away_team_id": 13,
       "matchDate": "2023-10-30",
       "posid": "NULL",
       "week": 3,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 15,
       "game_id": 2023020142,
       "home_team_id": 20,
       "away_team_id": 25,
       "matchDate": "2023-11-01",
       "posid": "NULL",
       "week": 3,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 16,
       "game_id": 2023020164,
       "home_team_id": 19,
       "away_team_id": 8,
       "matchDate": "2023-11-04",
       "posid": "NULL",
       "week": 4,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 17,
       "game_id": 2023020170,
       "home_team_id": 55,
       "away_team_id": 20,
       "matchDate": "2023-11-04",
       "posid": "NULL",
       "week": 4,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 18,
       "game_id": 2023020173,
       "home_team_id": 54,
       "away_team_id": 21,
       "matchDate": "2023-11-04",
       "posid": "NULL",
       "week": 4,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 19,
       "game_id": 2023020179,
       "home_team_id": 23,
       "away_team_id": 22,
       "matchDate": "2023-11-06",
       "posid": "NULL",
       "week": 4,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 20,
       "game_id": 2023020190,
       "home_team_id": 10,
       "away_team_id": 9,
       "matchDate": "2023-11-08",
       "posid": "NULL",
       "week": 4,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 21,
       "game_id": 2023020212,
       "home_team_id": 8,
       "away_team_id": 6,
       "matchDate": "2023-11-11",
       "posid": "NULL",
       "week": 5,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 22,
       "game_id": 2023020213,
       "home_team_id": 9,
       "away_team_id": 20,
       "matchDate": "2023-11-11",
       "posid": "NULL",
       "week": 5,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 23,
       "game_id": 2023020215,
       "home_team_id": 10,
       "away_team_id": 23,
       "matchDate": "2023-11-11",
       "posid": "NULL",
       "week": 5,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 24,
       "game_id": 2023020228,
       "home_team_id": 55,
       "away_team_id": 21,
       "matchDate": "2023-11-13",
       "posid": "NULL",
       "week": 5,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 25,
       "game_id": 2023020239,
       "home_team_id": 22,
       "away_team_id": 55,
       "matchDate": "2023-11-15",
       "posid": "NULL",
       "week": 5,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 26,
       "game_id": 2023020260,
       "home_team_id": 20,
       "away_team_id": 2,
       "matchDate": "2023-11-18",
       "posid": "NULL",
       "week": 6,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 27,
       "game_id": 2023020262,
       "home_team_id": 52,
       "away_team_id": 53,
       "matchDate": "2023-11-18",
       "posid": "NULL",
       "week": 6,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 28,
       "game_id": 2023020272,
       "home_team_id": 13,
       "away_team_id": 22,
       "matchDate": "2023-11-20",
       "posid": "NULL",
       "week": 6,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 29,
       "game_id": 2023020279,
       "home_team_id": 12,
       "away_team_id": 22,
       "matchDate": "2023-11-22",
       "posid": "NULL",
       "week": 6,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 30,
       "game_id": 2023020281,
       "home_team_id": 17,
       "away_team_id": 1,
       "matchDate": "2023-11-22",
       "posid": "NULL",
       "week": 6,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 31,
       "game_id": 2023020310,
       "home_team_id": 1,
       "away_team_id": 7,
       "matchDate": "2023-11-25",
       "posid": "NULL",
       "week": 7,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 32,
       "game_id": 2023020311,
       "home_team_id": 5,
       "away_team_id": 10,
       "matchDate": "2023-11-25",
       "posid": "NULL",
       "week": 7,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 33,
       "game_id": 2023020314,
       "home_team_id": 28,
       "away_team_id": 23,
       "matchDate": "2023-11-25",
       "posid": "NULL",
       "week": 7,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 34,
       "game_id": 2023020323,
       "home_team_id": 9,
       "away_team_id": 13,
       "matchDate": "2023-11-27",
       "posid": "NULL",
       "week": 7,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 35,
       "game_id": 2023020337,
       "home_team_id": 29,
       "away_team_id": 8,
       "matchDate": "2023-11-29",
       "posid": "NULL",
       "week": 7,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 36,
       "game_id": 2023020362,
       "home_team_id": 9,
       "away_team_id": 55,
       "matchDate": "2023-12-02",
       "posid": "NULL",
       "week": 8,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 37,
       "game_id": 2023020367,
       "home_team_id": 20,
       "away_team_id": 23,
       "matchDate": "2023-12-02",
       "posid": "NULL",
       "week": 8,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 38,
       "game_id": 2023020377,
       "home_team_id": 52,
       "away_team_id": 12,
       "matchDate": "2023-12-04",
       "posid": "NULL",
       "week": 8,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 39,
       "game_id": 2023020389,
       "home_team_id": 14,
       "away_team_id": 5,
       "matchDate": "2023-12-06",
       "posid": "NULL",
       "week": 8,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 40,
       "game_id": 2023020364,
       "home_team_id": 10,
       "away_team_id": 6,
       "matchDate": "2023-12-02",
       "week": 8,
       "banner": 1
      },
      {
       "id": 41,
       "game_id": 2023020411,
       "home_team_id": 7,
       "away_team_id": 8,
       "matchDate": "2023-12-09",
       "posid": "NULL",
       "week": 9,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 42,
       "game_id": 2023020412,
       "home_team_id": 17,
       "away_team_id": 9,
       "matchDate": "2023-12-09",
       "posid": "NULL",
       "week": 9,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 43,
       "game_id": 2023020419,
       "home_team_id": 23,
       "away_team_id": 12,
       "matchDate": "2023-12-09",
       "posid": "NULL",
       "week": 9,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 44,
       "game_id": 2023020429,
       "home_team_id": 2,
       "away_team_id": 10,
       "matchDate": "2023-12-11",
       "posid": "NULL",
       "week": 9,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 45,
       "game_id": 2023020445,
       "home_team_id": 21,
       "away_team_id": 7,
       "matchDate": "2023-12-13",
       "posid": "NULL",
       "week": 9,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 46,
       "game_id": 2023020471,
       "home_team_id": 20,
       "away_team_id": 14,
       "matchDate": "2023-12-16",
       "posid": "NULL",
       "week": 10,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 47,
       "game_id": 2023020472,
       "home_team_id": 22,
       "away_team_id": 13,
       "matchDate": "2023-12-16",
       "posid": "NULL",
       "week": 10,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 48,
       "game_id": 2023020480,
       "home_team_id": 5,
       "away_team_id": 30,
       "matchDate": "2023-12-18",
       "posid": "NULL",
       "week": 10,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 49,
       "game_id": 2023020481,
       "home_team_id": 52,
       "away_team_id": 8,
       "matchDate": "2023-12-18",
       "posid": "NULL",
       "week": 10,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 50,
       "game_id": 2023020495,
       "home_team_id": 52,
       "away_team_id": 17,
       "matchDate": "2023-12-20",
       "posid": "NULL",
       "week": 10,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 51,
       "game_id": 2023020517,
       "home_team_id": 29,
       "away_team_id": 10,
       "matchDate": "2023-12-23",
       "posid": "NULL",
       "week": 11,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 52,
       "game_id": 2023020526,
       "home_team_id": 26,
       "away_team_id": 20,
       "matchDate": "2023-12-23",
       "posid": "NULL",
       "week": 11,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 53,
       "game_id": 2023020527,
       "home_team_id": 23,
       "away_team_id": 28,
       "matchDate": "2023-12-23",
       "posid": "NULL",
       "week": 11,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 54,
       "game_id": 2023020531,
       "home_team_id": 10,
       "away_team_id": 9,
       "matchDate": "2023-12-27",
       "posid": "NULL",
       "week": 11,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 55,
       "game_id": 2023020536,
       "home_team_id": 19,
       "away_team_id": 25,
       "matchDate": "2023-12-27",
       "posid": "NULL",
       "week": 11,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 56,
       "game_id": 2023020558,
       "home_team_id": 13,
       "away_team_id": 8,
       "matchDate": "2023-12-30",
       "posid": "NULL",
       "week": 12,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 57,
       "game_id": 2023020561,
       "home_team_id": 10,
       "away_team_id": 12,
       "matchDate": "2023-12-30",
       "posid": "NULL",
       "week": 12,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 58,
       "game_id": 2023020563,
       "home_team_id": 26,
       "away_team_id": 22,
       "matchDate": "2023-12-30",
       "posid": "NULL",
       "week": 12,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 59,
       "game_id": 2023020579,
       "home_team_id": 18,
       "away_team_id": 16,
       "matchDate": "2024-01-02",
       "posid": "NULL",
       "week": 12,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 60,
       "game_id": 2023020588,
       "home_team_id": 24,
       "away_team_id": 10,
       "matchDate": "2024-01-03",
       "posid": "NULL",
       "week": 12,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 61,
       "game_id": 2023020610,
       "home_team_id": 8,
       "away_team_id": 3,
       "matchDate": "2024-01-06",
       "posid": "NULL",
       "week": 13,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 62,
       "game_id": 2023020611,
       "home_team_id": 1,
       "away_team_id": 23,
       "matchDate": "2024-01-06",
       "posid": "NULL",
       "week": 13,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 63,
       "game_id": 2023020615,
       "home_team_id": 22,
       "away_team_id": 9,
       "matchDate": "2024-01-06",
       "posid": "NULL",
       "week": 13,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 64,
       "game_id": 2023020616,
       "home_team_id": 54,
       "away_team_id": 2,
       "matchDate": "2024-01-06",
       "posid": "NULL",
       "week": 13,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 65,
       "game_id": 2023020635,
       "home_team_id": 4,
       "away_team_id": 8,
       "matchDate": "2024-01-10",
       "posid": "NULL",
       "week": 13,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 66,
       "game_id": 2023020660,
       "home_team_id": 8,
       "away_team_id": 22,
       "matchDate": "2024-01-13",
       "posid": "NULL",
       "week": 14,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 67,
       "game_id": 2023020663,
       "home_team_id": 52,
       "away_team_id": 4,
       "matchDate": "2024-01-13",
       "posid": "NULL",
       "week": 14,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 68,
       "game_id": 2023020668,
       "home_team_id": 54,
       "away_team_id": 20,
       "matchDate": "2024-01-13",
       "posid": "NULL",
       "week": 14,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 69,
       "game_id": 2023020678,
       "home_team_id": 8,
       "away_team_id": 21,
       "matchDate": "2024-01-15",
       "posid": "NULL",
       "week": 14,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 70,
       "game_id": 2023020691,
       "home_team_id": 7,
       "away_team_id": 16,
       "matchDate": "2024-01-17",
       "posid": "NULL",
       "week": 14,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 71,
       "game_id": 2023020710,
       "home_team_id": 6,
       "away_team_id": 8,
       "matchDate": "2024-01-20",
       "posid": "NULL",
       "week": 15,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 72,
       "game_id": 2023020712,
       "home_team_id": 23,
       "away_team_id": 10,
       "matchDate": "2024-01-20",
       "posid": "NULL",
       "week": 15,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 73,
       "game_id": 2023020714,
       "home_team_id": 20,
       "away_team_id": 22,
       "matchDate": "2024-01-20",
       "posid": "NULL",
       "week": 15,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 74,
       "game_id": 2023020739,
       "home_team_id": 13,
       "away_team_id": 53,
       "matchDate": "2024-01-24",
       "posid": "NULL",
       "week": 15,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 75,
       "game_id": 2023020740,
       "home_team_id": 10,
       "away_team_id": 52,
       "matchDate": "2024-01-24",
       "posid": "NULL",
       "week": 15,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 76,
       "game_id": 2023020768,
       "home_team_id": 52,
       "away_team_id": 10,
       "matchDate": "2024-01-27",
       "posid": "NULL",
       "week": 16,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 77,
       "game_id": 2023020770,
       "home_team_id": 30,
       "away_team_id": 24,
       "matchDate": "2024-01-27",
       "posid": "NULL",
       "week": 16,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 78,
       "game_id": 2023020771,
       "home_team_id": 20,
       "away_team_id": 16,
       "matchDate": "2024-01-27",
       "posid": "NULL",
       "week": 16,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 79,
       "game_id": 2023020772,
       "home_team_id": 23,
       "away_team_id": 29,
       "matchDate": "2024-01-27",
       "posid": "NULL",
       "week": 16,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 80,
       "game_id": 2023020778,
       "home_team_id": 17,
       "away_team_id": 9,
       "matchDate": "2024-01-31",
       "posid": "NULL",
       "week": 16,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 81,
       "game_id": 2023020782,
       "home_team_id": 10,
       "away_team_id": 2,
       "matchDate": "2024-02-05",
       "posid": "NULL",
       "week": 17,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 82,
       "game_id": 2023020785,
       "home_team_id": 12,
       "away_team_id": 23,
       "matchDate": "2024-02-06",
       "posid": "NULL",
       "week": 17,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 83,
       "game_id": 2023020788,
       "home_team_id": 5,
       "away_team_id": 52,
       "matchDate": "2024-02-06",
       "posid": "NULL",
       "week": 17,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 84,
       "game_id": 2023020792,
       "home_team_id": 10,
       "away_team_id": 25,
       "matchDate": "2024-02-07",
       "posid": "NULL",
       "week": 17,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 85,
       "game_id": 2023020793,
       "home_team_id": 16,
       "away_team_id": 30,
       "matchDate": "2024-02-07",
       "posid": "NULL",
       "week": 17,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 86,
       "game_id": 2023020812,
       "home_team_id": 9,
       "away_team_id": 10,
       "matchDate": "2024-02-10",
       "posid": "NULL",
       "week": 18,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 87,
       "game_id": 2023020816,
       "home_team_id": 26,
       "away_team_id": 22,
       "matchDate": "2024-02-10",
       "posid": "NULL",
       "week": 18,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 88,
       "game_id": 2023020820,
       "home_team_id": 3,
       "away_team_id": 20,
       "matchDate": "2024-02-12",
       "posid": "NULL",
       "week": 18,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 89,
       "game_id": 2023020821,
       "home_team_id": 4,
       "away_team_id": 53,
       "matchDate": "2024-02-12",
       "posid": "NULL",
       "week": 18,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 90,
       "game_id": 2023020835,
       "home_team_id": 52,
       "away_team_id": 28,
       "matchDate": "2024-02-14",
       "posid": "NULL",
       "week": 18,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 91,
       "game_id": 2023020908,
       "home_team_id": 21,
       "away_team_id": 10,
       "matchDate": "2024-02-24",
       "posid": "NULL",
       "week": 19,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 92,
       "game_id": 2023020911,
       "home_team_id": 23,
       "away_team_id": 6,
       "matchDate": "2024-02-24",
       "posid": "NULL",
       "week": 19,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 93,
       "game_id": 2023020912,
       "home_team_id": 22,
       "away_team_id": 20,
       "matchDate": "2024-02-24",
       "posid": "NULL",
       "week": 19,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 94,
       "game_id": 2023020919,
       "home_team_id": 29,
       "away_team_id": 3,
       "matchDate": "2024-02-25",
       "posid": "NULL",
       "week": 19,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 95,
       "game_id": 2023020940,
       "home_team_id": 22,
       "away_team_id": 19,
       "matchDate": "2024-02-28",
       "posid": "NULL",
       "week": 19,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 96,
       "game_id": 2023020962,
       "home_team_id": 4,
       "away_team_id": 9,
       "matchDate": "2024-03-02",
       "posid": "NULL",
       "week": 20,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 97,
       "game_id": 2023020963,
       "home_team_id": 14,
       "away_team_id": 8,
       "matchDate": "2024-03-02",
       "posid": "NULL",
       "week": 20,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 98,
       "game_id": 2023020968,
       "home_team_id": 20,
       "away_team_id": 5,
       "matchDate": "2024-03-02",
       "posid": "NULL",
       "week": 20,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 99,
       "game_id": 2023020978,
       "home_team_id": 10,
       "away_team_id": 6,
       "matchDate": "2024-03-04",
       "posid": "NULL",
       "week": 20,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 100,
       "game_id": 2023020989,
       "home_team_id": 28,
       "away_team_id": 25,
       "matchDate": "2024-03-05",
       "posid": "NULL",
       "week": 20,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 101,
       "game_id": 2023021014,
       "home_team_id": 8,
       "away_team_id": 10,
       "matchDate": "2024-03-09",
       "posid": "NULL",
       "week": 21,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 102,
       "game_id": 2023021015,
       "home_team_id": 28,
       "away_team_id": 9,
       "matchDate": "2024-03-09",
       "posid": "NULL",
       "week": 21,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 103,
       "game_id": 2023021019,
       "home_team_id": 23,
       "away_team_id": 52,
       "matchDate": "2024-03-09",
       "posid": "NULL",
       "week": 21,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 104,
       "game_id": 2023021028,
       "home_team_id": 3,
       "away_team_id": 1,
       "matchDate": "2024-03-11",
       "posid": "NULL",
       "week": 21,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 105,
       "game_id": 2023021042,
       "home_team_id": 52,
       "away_team_id": 18,
       "matchDate": "2024-03-13",
       "posid": "NULL",
       "week": 21,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 106,
       "game_id": 2023021066,
       "home_team_id": 20,
       "away_team_id": 8,
       "matchDate": "2024-03-16",
       "posid": "NULL",
       "week": 22,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 107,
       "game_id": 2023021070,
       "home_team_id": 22,
       "away_team_id": 21,
       "matchDate": "2024-03-16",
       "posid": "NULL",
       "week": 22,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 108,
       "game_id": 2023021072,
       "home_team_id": 23,
       "away_team_id": 15,
       "matchDate": "2024-03-16",
       "posid": "NULL",
       "week": 22,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 109,
       "game_id": 2023021095,
       "home_team_id": 15,
       "away_team_id": 10,
       "matchDate": "2024-03-20",
       "posid": "NULL",
       "week": 22,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 110,
       "game_id": 2023021097,
       "home_team_id": 26,
       "away_team_id": 30,
       "matchDate": "2024-03-20",
       "posid": "NULL",
       "week": 22,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 111,
       "game_id": 2023021117,
       "home_team_id": 1,
       "away_team_id": 9,
       "matchDate": "2024-03-23",
       "posid": "NULL",
       "week": 23,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 112,
       "game_id": 2023021118,
       "home_team_id": 10,
       "away_team_id": 22,
       "matchDate": "2024-03-23",
       "posid": "NULL",
       "week": 23,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 113,
       "game_id": 2023021120,
       "home_team_id": 23,
       "away_team_id": 20,
       "matchDate": "2024-03-23",
       "posid": "NULL",
       "week": 23,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 114,
       "game_id": 2023021135,
       "home_team_id": 23,
       "away_team_id": 26,
       "matchDate": "2024-03-25",
       "posid": "NULL",
       "week": 23,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 115,
       "game_id": 2023021138,
       "home_team_id": 5,
       "away_team_id": 12,
       "matchDate": "2024-03-26",
       "posid": "NULL",
       "week": 23,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 116,
       "game_id": 2023021172,
       "home_team_id": 8,
       "away_team_id": 12,
       "matchDate": "2024-03-30",
       "posid": "NULL",
       "week": 24,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 117,
       "game_id": 2023021175,
       "home_team_id": 52,
       "away_team_id": 9,
       "matchDate": "2024-03-30",
       "posid": "NULL",
       "week": 24,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 118,
       "game_id": 2023021178,
       "home_team_id": 20,
       "away_team_id": 26,
       "matchDate": "2024-03-30",
       "posid": "NULL",
       "week": 24,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 119,
       "game_id": 2023021192,
       "home_team_id": 2,
       "away_team_id": 16,
       "matchDate": "2024-04-02",
       "posid": "NULL",
       "week": 24,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 120,
       "game_id": 2023021197,
       "home_team_id": 10,
       "away_team_id": 14,
       "matchDate": "2024-04-03",
       "posid": "NULL",
       "week": 24,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 121,
       "game_id": 2023021223,
       "home_team_id": 8,
       "away_team_id": 10,
       "matchDate": "2024-04-06",
       "posid": "NULL",
       "week": 25,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 122,
       "game_id": 2023021226,
       "home_team_id": 20,
       "away_team_id": 22,
       "matchDate": "2024-04-06",
       "posid": "NULL",
       "week": 25,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 123,
       "game_id": 2023021237,
       "home_team_id": 10,
       "away_team_id": 5,
       "matchDate": "2024-04-08",
       "posid": "NULL",
       "week": 25,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 124,
       "game_id": 2023021244,
       "home_team_id": 2,
       "away_team_id": 3,
       "matchDate": "2024-04-09",
       "posid": "NULL",
       "week": 25,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 125,
       "game_id": 2023021253,
       "home_team_id": 22,
       "away_team_id": 54,
       "matchDate": "2024-04-10",
       "posid": "NULL",
       "week": 25,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 126,
       "game_id": 2023021276,
       "home_team_id": 9,
       "away_team_id": 8,
       "matchDate": "2024-04-13",
       "posid": "NULL",
       "week": 26,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 127,
       "game_id": 2023021280,
       "home_team_id": 22,
       "away_team_id": 23,
       "matchDate": "2024-04-13",
       "posid": "NULL",
       "week": 26,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 128,
       "game_id": 2023021287,
       "home_team_id": 17,
       "away_team_id": 8,
       "matchDate": "2024-04-15",
       "posid": "NULL",
       "week": 26,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 129,
       "game_id": 2023021294,
       "home_team_id": 26,
       "away_team_id": 30,
       "matchDate": "2024-04-15",
       "posid": "NULL",
       "week": 26,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      },
      {
       "id": 130,
       "game_id": 2023021304,
       "home_team_id": 14,
       "away_team_id": 10,
       "matchDate": "2024-04-17",
       "posid": "NULL",
       "week": 26,
       "banner": 1,
       "winner": "NULL",
       "cancel": "NULL",
       "lastUpdated": "NULL"
      }
   ]
   
   ), "RESULTTTT")




